#version: "2"
name: nnmbot
services:
  nnmbot_fe:
    image: dimania/nnmbot
    command: python frontend_nnmbot.py
        
    volumes:
          # mount config file
        - type: bind
          source: /home/dima/src/nnmbot/myconfig.cfg
          target: /home/nnmbot/myconfig.cfg
          read_only: true
          
          # mount dir for database file
          # settings path file database must be changed in config file!
        - type: bind
          source: /home/dima/src/nnmbot/data
          target: /home/nnmbot/data
        
          # mount dir for logs
          # settings path log file must be changed in config file!
        - type: bind
          source: /home/dima/src/nnmbot/log
          target: /home/nnmbot/log

          # mount dir for session telegram file if need
          # settings path log file must be changed in config file!
        - type: bind
          source: /home/dima/src/nnmbot/session
          target: /home/nnmbot/session
          
    # Critical secret keys can set over env vars 
    env_file:
        - path: ./config_over_env.env
          format: raw

  nnmbot_be:
    image: dimania/nnmbot
    command: python backend_nnmbot.py
    
    
    volumes:
          # mount config file
        - type: bind
          source: /home/dima/src/nnmbot/myconfig.cfg
          target: /home/nnmbot/myconfig.cfg
          read_only: true
          
          # mount dir for database file
          # settings path file database must be changed in config file!
        - type: bind
          source: /home/dima/src/nnmbot/data
          target: /home/nnmbot/data
        
          # mount dir for logs
          # settings path log file must be changed in config file!
        - type: bind
          source: /home/dima/src/nnmbot/log
          target: /home/nnmbot/log

          # mount dir for session telegram file if need
          # settings path log file must be changed in config file!
        - type: bind
          source: /home/dima/src/nnmbot/session
          target: /home/nnmbot/session

          
    # Critical secret keys can set over env vars 
    env_file:
        - path: ./config_over_env.env
          format: raw
